on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run build

      - run: npx graph auth --product hosted-service ${{ secrets.GRAPH_HOSTED_TOKEN }}
      - run: npm run prepare:optimism
      - run: npx graph deploy --product hosted-service exactly/optimism

      - run: npx graph auth --studio ${{ secrets.GRAPH_STUDIO_TOKEN }}
      - run: npm run prepare:mainnet
      - run: npx graph deploy --studio -l {{ github.ref_name }} exactly
